cc_library(
    name = "rs-common",
    hdrs = glob([
        "include/rs/common/Exception.h",
        "include/rs/common/utility/TaggedInteger.h",
        "include/rs/common/utility/VariantVisitor.h",
    ]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = ["@conan_fmt//:fmt"],
)
